# Generated by Django 5.1.1 on 2024-09-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "patient_id",
                    models.CharField(
                        db_column="PatientID",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_column="Date")),
                ("age", models.IntegerField(db_column="Age")),
                ("gender", models.CharField(db_column="Gender", max_length=10)),
                ("diagnosis", models.CharField(db_column="Diagnosis", max_length=100)),
                ("lab_results", models.FloatField(db_column="LabResults")),
                (
                    "medication",
                    models.CharField(
                        blank=True, db_column="Medication", max_length=100, null=True
                    ),
                ),
                ("visit_type", models.CharField(db_column="VisitType", max_length=50)),
                ("outcome", models.CharField(db_column="Outcome", max_length=50)),
            ],
            options={
                "db_table": "patient_data",
            },
        ),
    ]
